
AppBundle_admin_cycle:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_cycle.yml"
    prefix:   /cycle

AppBundle_admin_pack:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_pack.yml"
    prefix:   /pack

AppBundle_admin_card:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_card.yml"
    prefix:   /card
    
AppBundle_excel:
    resource: "@AppBundle/Resources/config/routing/admin/routing_admin_excel.yml"
    prefix:   /excel
    
all_comments:
    pattern: /deckcomments/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:comments
        page: 1
    
user_comments:
    pattern: /user/comments/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:usercomments
        page: 1
        