remind_email:
    path:     /remind/{username}
    defaults:
        _controller: AppBundle:User:remind

card_reviews_list_byauthor:
    pattern: /reviews/{user_id}/{page}
    defaults:
        _controller: AppBundle:Review:byauthor
        page: 1
    requirements:
        page: \d+
        user_id: \d+

user_profile:
    pattern: /profile
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:profile

user_profile_view:
    pattern: /profile/{user_id}/{user_name}/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:profile
        page: 1
    requirements:
        user_id: \d+

decklist_favorite:
    pattern: /favorite
    methods: [POST]
    defaults:
        _controller: AppBundle:Social:favorite

decklist_like:
    pattern: /like
    methods: [POST]
    defaults:
        _controller: AppBundle:Social:vote

decklist_comment:
    pattern: /comment
    methods: [POST]
    defaults:
        _controller: AppBundle:Social:comment

decklist_comment_hide:
    pattern: /hidecomment/{comment_id}/{hidden}
    methods: [POST]
    defaults:
        _controller: AppBundle:Social:hidecomment

user_profile_save:
    pattern: /profile_save
    methods: [POST]
    defaults:
        _controller: AppBundle:Default:saveProfile
        
user_info:
    pattern: /info
    defaults:
        _controller: AppBundle:User:info
        