app_admin:
    resource: "@AppBundle/Resources/config/routing/routing_admin.yml"
    prefix: /admin

app_api:
    resource: "@AppBundle/Resources/config/routing/routing_api.yml"
    prefix: /{_locale}/api

app_cards:
    resource: "@AppBundle/Resources/config/routing/routing_cards.yml"
    prefix: /{_locale}

app_deck:
    resource: "@AppBundle/Resources/config/routing/routing_deck.yml"
    prefix: /{_locale}/deck

app_decklist:
    resource: "@AppBundle/Resources/config/routing/routing_decklist.yml"
    prefix: /decklist

app_review:
    resource: "@AppBundle/Resources/config/routing/routing_review.yml"
    prefix: /review

app_tag:
    resource: "@AppBundle/Resources/config/routing/routing_tag.yml"
    prefix: /tag

app_user:
    resource: "@AppBundle/Resources/config/routing/routing_user.yml"
    prefix: /user

index:
    path: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:index

donators:
    path: /donators
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:donators

decks_list:
    path: /{_locale}/decks
    methods: [GET]
    defaults:
        _controller: AppBundle:Builder:list

decklists_searchform:
    path: /decklists/search
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:search

decklists_list:
    path: /decklists/{type}/{page}
    methods: [GET]
    defaults:
        _controller: AppBundle:Social:list
        type: popular
        page: 1
    requirements:
        page: \d+

card_reviews_list:
    path: /reviews/{page}
    defaults:
        _controller: AppBundle:Review:list
        page: 1
    requirements:
        page: \d+

about:
    path: /about
    defaults:
        _controller: AppBundle:Default:about

rules:
    path: /rules
    defaults:
        _controller: AppBundle:Default:rules

ffg:
    path: /ffg
    defaults:
        _controller: AppBundle:Default:ffg
