services:
    decks:
        class: AppBundle\Services\Decks
        arguments: ["@doctrine.orm.entity_manager", "@deck_interface", "@diff", "@logger"]
    highlight:
        class: AppBundle\Services\Highlight
        arguments: ["@doctrine.orm.entity_manager"]
    decklists:
        class: AppBundle\Services\Decklists
        arguments: ["@doctrine.orm.entity_manager", "@deck_interface"]
    deck_interface:
        class: AppBundle\Services\DeckInterface
        arguments: ["@doctrine.orm.entity_manager"]
    reviews:
        class: AppBundle\Services\Reviews
        arguments: ["@doctrine.orm.entity_manager"]
    texts:
        class: AppBundle\Services\Texts
        arguments: ["%kernel.root_dir%"]
    diff:
        class: AppBundle\Services\Diff
        arguments: ["@doctrine.orm.entity_manager"]
    cards_data:
        class: AppBundle\Services\CardsData
        arguments: ["@doctrine", "@request_stack", "@router", "@templating.helper.assets", "%kernel.root_dir%"]
    decklist_manager:
        class: AppBundle\Model\DecklistManager
        scope: prototype
        arguments: ["@doctrine.orm.entity_manager", "@request_stack", "@router", "@deck_interface", "@logger"]
    agenda_helper:
        class: AppBundle\Helper\AgendaHelper
        arguments: ["@doctrine.orm.entity_manager"]
    deck_validation_helper:
        class: AppBundle\Helper\DeckValidationHelper
        arguments: ["@agenda_helper"]
