parameters:
    decks.class: AppBundle\Services\Decks
    highlight.class: AppBundle\Services\Highlight
    decklists.class: AppBundle\Services\Decklists
    deck_interface.class: AppBundle\Services\DeckInterface
    reviews.class: AppBundle\Services\Reviews
    texts.class: AppBundle\Services\Texts
    diff.class: AppBundle\Services\Diff
    cards_data.class: AppBundle\Services\CardsData
    octgn.class: AppBundle\Services\Octgn

services:
    decks:
        class: "%decks.class%"
        arguments: ["@doctrine.orm.entity_manager", "@deck_interface", "@diff", "@logger"]
    highlight:
        class: "%highlight.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    decklists:
        class: "%decklists.class%"
        arguments: ["@doctrine.orm.entity_manager", "@deck_interface"]
    deck_interface:
        class: "%deck_interface.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    reviews:
        class: "%reviews.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    texts:
        class: "%texts.class%"
        arguments: ["%kernel.root_dir%"]
    diff:
        class: "%diff.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    cards_data:
        class: "%cards_data.class%"
        arguments: ["@doctrine", "@request_stack", "@router", "@templating.helper.assets", "%kernel.root_dir%"]
    octgn:
        class: "%octgn.class%"
        arguments: ["@doctrine.orm.entity_manager", "@twig"]
